### PR TITLE
Added Enemy Patrol

### PR DESCRIPTION
**Pull request by RyanFloresTT**

### CODE REVIEW

**Review by robbyklein — DISMISSED** [review]
Nice nice

**Review by robbyklein — APPROVED** [review]

**Review by robbyklein — DISMISSED** [review]
Why wont my review count?

**Review by robbyklein — APPROVED** [review]
Trying this again

**Review by RyanFloresTT — COMMENTED** [review]
testing

**Review by robbyklein — DISMISSED** [review]
approval!

**Pull request merged**
